locals {
  resource_group_name            = "${var.name}-rg"
  key_vault_key_name             = "${var.name}-vaultkey1"
  disk_encryption_set            = "${var.name}-disk-encryption-set"
  log_analytics_workspace_name   = "${var.name}-log-analytics-workspace"
  aks_node_pool_name             = "snp"
  temporary_np_name_for_rotation = "tnp"
  windows_node_pood_name_prefix  = "wnp"
  linux_node_pood_name_prefix    = "lnp"
  acr_user_assigned_identity     = "${var.name}-uai"
  user_assigned_identity         = "${var.name}-aks-uai"
  zone_group                     = "${var.name}-zone-group"
  aks_private_connection         = "${var.name}-private-connection"
  container_insights             = "${var.name}-container_insights"
  disk_crypto_key                = "${var.name}-disk-vaultkey"
  k8s_dns_zone_rg                = "${var.k8s_dns_zone}-rg"
  use_kv                         = var.ems_kv != ""
  use_appgw                      = var.appgw != ""
}
